on: 
  push:
    branches:
      - "production"  # Trigger on push to the production branch

name: Deploy website on push

jobs:
  web-deploy:
    name: Deploy to main website and prod.hekinav
    runs-on: ubuntu-latest
    
    steps:
    # Step to get the latest code
    - name: Get latest code
      uses: actions/checkout@v4

    # Step to set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    # Step to upload to prod.hekinav (before minification)
    - name: Upload to prod.hekinav
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpupload.net
        username: if0_35306213
        password: ${{ secrets.ftppassword }}
        protocol: ftp
        server-dir: ./prod.hekinav42web.io/htdocs/
        
    # Step to minify HTML, CSS, and JS
    - name: Minify HTML, CSS, and JS
      run: |
        # Install minification tools
        npm install -g html-minifier-terser clean-css-cli terser
        
        # Minify HTML files (use the correct command for html-minifier)
        find ./ -name "*.html" -exec html-minifier-terser --collapse-whitespace --remove-comments --minify-js true --minify-css true {} -o {} \;
        
        # Minify CSS files
        find ./ -name "*.css" -exec cleancss -o {} {} \;
        
        # Minify JS files
        find ./ -name "*.js" -exec terser {} --compress --mangle -o {} \;

    # Step to upload to main website
    - name: Upload to hekinav main website
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpupload.net
        username: if0_35306213
        password: ${{ secrets.ftppassword }}
        protocol: ftp
        server-dir: ./htdocs/
