on: 
  push:
    branches:
      - "production"
name: Deploy website on push
jobs:
    
  web-deploy:
    name: Deploy to main website and prod.hekinav
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    - name: Upload to prod.hekinav
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpupload.net
        username: if0_35306213
        password: ${{ secrets.ftppassword }}
        protocol: ftp
        server-dir: ./prod.hekinav42web.io/htdocs/
    - name: Minify Action
      uses: anthonyftwang/minify-action@v1.0.1
    - name: Upload to hekinav main website
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpupload.net
        username: if0_35306213
        password: ${{ secrets.ftppassword }}
        protocol: ftp
        server-dir: ./htdocs/
